#!/usr/bin/env bash
# debateos-install.sh — generated by DebateOS Arch translator
# Fully-unattended Arch installer: reads build-manifest.json with jq.
# No opinion data is shell-interpolated (Pitfall 6 / T-02-09).
# Generated %%ISO_LABEL%%; SOURCE_DATE_EPOCH=%%SOURCE_DATE_EPOCH%%
set -euo pipefail

MANIFEST="/root/build-manifest.json"
LOGFILE="/root/install.log"

if [[ ! -f "$MANIFEST" ]]; then
    echo "ERROR: $MANIFEST not found. Installer cannot continue." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Target disk selection
# ---------------------------------------------------------------------------
TARGET_DISK="${TARGET_DISK:-/dev/sda}"
if [[ ! -b "$TARGET_DISK" ]]; then
    # Try the first available non-removable block device
    TARGET_DISK=$(lsblk -dpno NAME,TYPE,RM | awk '$2=="disk" && $3==0 {print $1; exit}')
    if [[ -z "$TARGET_DISK" ]]; then
        echo "ERROR: No suitable target disk found. Set TARGET_DISK env var." >&2
        exit 1
    fi
fi
echo "Target disk: $TARGET_DISK"

# ---------------------------------------------------------------------------
# Partitioning (single-disk, GPT: 512M EFI + rest btrfs root)
# ---------------------------------------------------------------------------
sgdisk --zap-all "$TARGET_DISK"
sgdisk -n 1:0:+512M -t 1:ef00 -c 1:"EFI System" "$TARGET_DISK"
sgdisk -n 2:0:0 -t 2:8300 -c 2:"Linux root" "$TARGET_DISK"
partprobe "$TARGET_DISK"
sleep 1

EFI_PART="${TARGET_DISK}1"
ROOT_PART="${TARGET_DISK}2"

# Format
mkfs.fat -F32 -n EFI "$EFI_PART"
mkfs.btrfs -f -L debateos "$ROOT_PART"

# Mount btrfs and create subvolumes
mount "$ROOT_PART" /mnt
btrfs subvolume create /mnt/@
btrfs subvolume create /mnt/@home
btrfs subvolume create /mnt/@snapshots
umount /mnt

mount -o noatime,compress=zstd,subvol=@ "$ROOT_PART" /mnt
mkdir -p /mnt/{home,.snapshots,boot/efi}
mount -o noatime,compress=zstd,subvol=@home "$ROOT_PART" /mnt/home
mount -o noatime,compress=zstd,subvol=@snapshots "$ROOT_PART" /mnt/.snapshots
mount "$EFI_PART" /mnt/boot/efi

# ---------------------------------------------------------------------------
# Keyring packages first (variant keyring_install_before_repos, Pitfall 4)
# ---------------------------------------------------------------------------
KEYRING_PKGS=$(jq -r '.keyring_install_before_repos // [] | .[]' "$MANIFEST" 2>/dev/null || true)
if [[ -n "$KEYRING_PKGS" ]]; then
    echo "Installing keyring packages first..."
    # shellcheck disable=SC2086
    pacman -Sy --noconfirm $KEYRING_PKGS
fi

# ---------------------------------------------------------------------------
# pacstrap the target with the resolved package set from build-manifest.json
# ---------------------------------------------------------------------------
TARGET_PKGS=$(jq -r '.target_packages | .[]' "$MANIFEST")
echo "Running pacstrap with target package set..."
# shellcheck disable=SC2086
pacstrap -K /mnt base linux linux-firmware $TARGET_PKGS --noconfirm

# ---------------------------------------------------------------------------
# fstab
# ---------------------------------------------------------------------------
genfstab -U /mnt >> /mnt/etc/fstab

# ---------------------------------------------------------------------------
# Basic system config
# ---------------------------------------------------------------------------
arch-chroot /mnt ln -sf /usr/share/zoneinfo/UTC /etc/localtime
arch-chroot /mnt hwclock --systohc
echo "en_US.UTF-8 UTF-8" >> /mnt/etc/locale.gen
arch-chroot /mnt locale-gen
echo "LANG=en_US.UTF-8" > /mnt/etc/locale.conf
echo "debateos" > /mnt/etc/hostname

# ---------------------------------------------------------------------------
# Enable system services from build-manifest.json
# ---------------------------------------------------------------------------
SYSTEM_SERVICES=$(jq -r '.system_services | .[] | select(.action=="enable") | .name' "$MANIFEST")
for svc in $SYSTEM_SERVICES; do
    echo "Enabling service: $svc"
    arch-chroot /mnt systemctl enable "$svc" || true
done

# ---------------------------------------------------------------------------
# Group memberships from build-manifest.json
# ---------------------------------------------------------------------------
GROUPS=$(jq -r '.group_memberships | .[] | .group' "$MANIFEST" 2>/dev/null || true)
for grp in $GROUPS; do
    arch-chroot /mnt groupadd -f "$grp" || true
done

# ---------------------------------------------------------------------------
# sysctl drop-ins from build-manifest.json
# ---------------------------------------------------------------------------
SYSCTL_COUNT=$(jq '.sysctl_params | length' "$MANIFEST")
if [[ "$SYSCTL_COUNT" -gt 0 ]]; then
    mkdir -p /mnt/etc/sysctl.d
    jq -r '.sysctl_params | group_by(.drop_in_file) | .[] | {file: .[0].drop_in_file, params: .} | @json' "$MANIFEST" | while IFS= read -r group_json; do
        drop_file=$(echo "$group_json" | jq -r '.file')
        echo "$group_json" | jq -r '.params[] | "\(.key) = \(.value)"' >> "/mnt/etc/sysctl.d/$drop_file"
    done
fi

# ---------------------------------------------------------------------------
# Copy build-manifest.json to target for first-run unit access
# ---------------------------------------------------------------------------
mkdir -p /mnt/var/lib/debateos
cp "$MANIFEST" /mnt/var/lib/debateos/build-manifest.json

# ---------------------------------------------------------------------------
# initramfs
# ---------------------------------------------------------------------------
arch-chroot /mnt mkinitcpio -P

echo "DebateOS installation complete."
