#!/usr/bin/env bash
# debateos-install.sh — generated by DebateOS Arch translator
# Fully-unattended Arch installer: reads build-manifest.json with jq.
# No opinion data is shell-interpolated (Pitfall 6 / T-02-09).
# Generated %%ISO_LABEL%%; SOURCE_DATE_EPOCH=%%SOURCE_DATE_EPOCH%%
set -euo pipefail

MANIFEST="/root/build-manifest.json"
LOGFILE="/root/install.log"

if [[ ! -f "$MANIFEST" ]]; then
    echo "ERROR: $MANIFEST not found. Installer cannot continue." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Target disk selection
# ---------------------------------------------------------------------------
TARGET_DISK="${TARGET_DISK:-/dev/sda}"
if [[ ! -b "$TARGET_DISK" ]]; then
    # Try the first available non-removable block device
    TARGET_DISK=$(lsblk -dpno NAME,TYPE,RM | awk '$2=="disk" && $3==0 {print $1; exit}')
    if [[ -z "$TARGET_DISK" ]]; then
        echo "ERROR: No suitable target disk found. Set TARGET_DISK env var." >&2
        exit 1
    fi
fi
echo "Target disk: $TARGET_DISK"

# ---------------------------------------------------------------------------
# Partitioning (single-disk, GPT: 512M EFI + rest btrfs root)
# ---------------------------------------------------------------------------
sgdisk --zap-all "$TARGET_DISK"
sgdisk -n 1:0:+512M -t 1:ef00 -c 1:"EFI System" "$TARGET_DISK"
sgdisk -n 2:0:0 -t 2:8300 -c 2:"Linux root" "$TARGET_DISK"
partprobe "$TARGET_DISK"
sleep 1

# CR-03: Determine partition suffix — NVMe/loop devices need a 'p' separator.
# (e.g. /dev/nvme0n1 → /dev/nvme0n1p1; /dev/sda → /dev/sda1)
if [[ "$TARGET_DISK" =~ nvme|loop ]]; then
    EFI_PART="${TARGET_DISK}p1"
    ROOT_PART="${TARGET_DISK}p2"
else
    EFI_PART="${TARGET_DISK}1"
    ROOT_PART="${TARGET_DISK}2"
fi

# Format
mkfs.fat -F32 -n EFI "$EFI_PART"
mkfs.btrfs -f -L debateos "$ROOT_PART"

# Mount btrfs and create subvolumes
mount "$ROOT_PART" /mnt
btrfs subvolume create /mnt/@
btrfs subvolume create /mnt/@home
btrfs subvolume create /mnt/@snapshots
umount /mnt

mount -o noatime,compress=zstd,subvol=@ "$ROOT_PART" /mnt
mkdir -p /mnt/{home,.snapshots,boot/efi}
mount -o noatime,compress=zstd,subvol=@home "$ROOT_PART" /mnt/home
mount -o noatime,compress=zstd,subvol=@snapshots "$ROOT_PART" /mnt/.snapshots
mount "$EFI_PART" /mnt/boot/efi

# ---------------------------------------------------------------------------
# Keyring packages first (variant keyring_install_before_repos, Pitfall 4)
# ---------------------------------------------------------------------------
KEYRING_PKGS=$(jq -r '.keyring_install_before_repos // [] | .[]' "$MANIFEST" 2>/dev/null || true)
if [[ -n "$KEYRING_PKGS" ]]; then
    echo "Installing keyring packages first..."
    # shellcheck disable=SC2086
    pacman -Sy --noconfirm $KEYRING_PKGS
fi

# ---------------------------------------------------------------------------
# CR-01: Configure custom repos in live env pacman.conf BEFORE pacstrap
# ---------------------------------------------------------------------------
# Read custom_repos from build-manifest.json and:
# 1. Import each repo's GPG key fingerprint (keyring field)
# 2. Append the repo section to /etc/pacman.conf (live env)
# 3. Also append to /mnt/etc/pacman.conf (target) for post-install pacman use
# 4. Sync the new repo databases
CUSTOM_REPOS=$(jq -c '.custom_repos // []' "$MANIFEST")
if [[ "$(echo "$CUSTOM_REPOS" | jq 'length')" -gt 0 ]]; then
    echo "Configuring custom repos in live env pacman.conf..."
    echo "$CUSTOM_REPOS" | jq -r '.[] | .keyring // empty' | while read -r key; do
        if [[ -n "$key" ]]; then
            echo "Importing GPG key: $key"
            pacman-key --recv-keys "$key" || true
            pacman-key --lsign-key "$key" || true
        fi
    done
    # Append repo sections to live /etc/pacman.conf
    echo "$CUSTOM_REPOS" | jq -r '.[] |
        "# sig_level=" + .sig_level,
        "[" + .name + "]",
        "Server = " + .url,
        "SigLevel = " + .sig_level,
        ""' \
        >> /etc/pacman.conf
    pacman -Sy --noconfirm
fi

# ---------------------------------------------------------------------------
# pacstrap the target with the resolved package set from build-manifest.json
# ---------------------------------------------------------------------------
TARGET_PKGS=$(jq -r '.target_packages | .[]' "$MANIFEST")
echo "Running pacstrap with target package set..."
# shellcheck disable=SC2086
pacstrap -K /mnt base linux linux-firmware $TARGET_PKGS --noconfirm

# ---------------------------------------------------------------------------
# fstab
# ---------------------------------------------------------------------------
genfstab -U /mnt >> /mnt/etc/fstab

# ---------------------------------------------------------------------------
# Basic system config
# ---------------------------------------------------------------------------
arch-chroot /mnt ln -sf /usr/share/zoneinfo/UTC /etc/localtime
arch-chroot /mnt hwclock --systohc
echo "en_US.UTF-8 UTF-8" >> /mnt/etc/locale.gen
arch-chroot /mnt locale-gen
echo "LANG=en_US.UTF-8" > /mnt/etc/locale.conf
echo "debateos" > /mnt/etc/hostname

# ---------------------------------------------------------------------------
# Enable system services from build-manifest.json
# ---------------------------------------------------------------------------
SYSTEM_SERVICES=$(jq -r '.system_services | .[] | select(.action=="enable") | .name' "$MANIFEST")
for svc in $SYSTEM_SERVICES; do
    echo "Enabling service: $svc"
    arch-chroot /mnt systemctl enable "$svc" || true
done

# ---------------------------------------------------------------------------
# Group memberships from build-manifest.json
# ---------------------------------------------------------------------------
GROUPS=$(jq -r '.group_memberships | .[] | .group' "$MANIFEST" 2>/dev/null || true)
for grp in $GROUPS; do
    arch-chroot /mnt groupadd -f "$grp" || true
done

# ---------------------------------------------------------------------------
# sysctl drop-ins from build-manifest.json
# ---------------------------------------------------------------------------
SYSCTL_COUNT=$(jq '.sysctl_params | length' "$MANIFEST")
if [[ "$SYSCTL_COUNT" -gt 0 ]]; then
    mkdir -p /mnt/etc/sysctl.d
    jq -r '.sysctl_params | group_by(.drop_in_file) | .[] | {file: .[0].drop_in_file, params: .} | @json' "$MANIFEST" | while IFS= read -r group_json; do
        # WR-03: Default drop_in_file to 99-debateos.conf when field is null/absent
        drop_file=$(echo "$group_json" | jq -r '.file // "99-debateos.conf"')
        if [[ -z "$drop_file" || "$drop_file" == "null" ]]; then
            drop_file="99-debateos.conf"
        fi
        echo "$group_json" | jq -r '.params[] | "\(.key) = \(.value)"' >> "/mnt/etc/sysctl.d/$drop_file"
    done
fi

# ---------------------------------------------------------------------------
# Copy build-manifest.json to target for first-run unit access
# ---------------------------------------------------------------------------
mkdir -p /mnt/var/lib/debateos
cp "$MANIFEST" /mnt/var/lib/debateos/build-manifest.json

# ---------------------------------------------------------------------------
# initramfs
# ---------------------------------------------------------------------------
arch-chroot /mnt mkinitcpio -P

# ---------------------------------------------------------------------------
# CR-02: Bootloader installation (data-driven; no per-variant code forks)
# ---------------------------------------------------------------------------
BOOTLOADER=$(jq -r '.bootloader // ""' "$MANIFEST" 2>/dev/null || echo "")
if [[ "$BOOTLOADER" == "limine" ]] || jq -e '.target_packages | index("limine")' "$MANIFEST" >/dev/null 2>&1; then
    echo "Installing limine bootloader..."
    # limine BIOS install
    arch-chroot /mnt limine bios-install "$TARGET_DISK" || true
    # limine EFI install — copy EFI binary and create boot entry
    mkdir -p /mnt/boot/efi/EFI/limine
    cp /mnt/usr/share/limine/BOOTX64.EFI /mnt/boot/efi/EFI/limine/ 2>/dev/null || \
        cp /mnt/usr/share/limine/limine-bios.sys /mnt/boot/efi/EFI/limine/ 2>/dev/null || true
    # Register EFI boot entry
    arch-chroot /mnt efibootmgr --create \
        --disk "$TARGET_DISK" --part 1 \
        --label "DebateOS (limine)" \
        --loader '\EFI\limine\BOOTX64.EFI' || true
    # Write minimal limine.cfg if not already provided by packages
    if [[ ! -f /mnt/boot/limine.cfg ]]; then
        KERNEL_PARAMS=$(jq -r '.kernel_params // [] | map(.key + if .value != "" then "=" + .value else "" end) | join(" ")' "$MANIFEST" 2>/dev/null || echo "")
        cat > /mnt/boot/limine.cfg <<LIMINE_EOF
timeout=5

:DebateOS
  protocol=linux
  kernel_path=boot:///vmlinuz-linux
  cmdline=root=/dev/disk/by-label/debateos rootflags=subvol=@ rw ${KERNEL_PARAMS}
  module_path=boot:///initramfs-linux.img
LIMINE_EOF
    fi
else
    # Default: systemd-boot (vanilla-arch and others without limine)
    echo "Installing systemd-boot bootloader..."
    arch-chroot /mnt bootctl install
    # Write minimal loader entry
    KERNEL_PARAMS=$(jq -r '.kernel_params // [] | map(.key + if .value != "" then "=" + .value else "" end) | join(" ")' "$MANIFEST" 2>/dev/null || echo "")
    mkdir -p /mnt/boot/efi/loader/entries
    cat > /mnt/boot/efi/loader/loader.conf <<LOADER_EOF
default debateos.conf
timeout 5
console-mode max
LOADER_EOF
    cat > /mnt/boot/efi/loader/entries/debateos.conf <<ENTRY_EOF
title   DebateOS
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options root=/dev/disk/by-label/debateos rootflags=subvol=@ rw ${KERNEL_PARAMS}
ENTRY_EOF
fi

echo "DebateOS installation complete."
