#
# pacman.conf — generated by DebateOS Arch translator (archiso profile)
# Base repos follow standard Arch Linux pacman.conf (releng profile).
# Variant custom repos are injected above or below core/extra per above_core flag.
# Trust warnings appear as comments before any sig_level!=Required repo.
#
# WARNING: This pacman.conf is for the LIVE ISO build environment.
# The installer reads build-manifest.json and applies variant repos to the
# TARGET system at install time.
#

[options]
HoldPkg     = pacman glibc
Architecture = auto

Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

{variant_repos_above}
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

{variant_repos_below}
