#!/usr/bin/env bash
# profiledef.sh — generated by DebateOS Arch translator
# Source: /usr/share/archiso/configs/releng/profiledef.sh (archiso 88-1)
# Modified for DebateOS; SOURCE_DATE_EPOCH={source_date_epoch}

iso_name="debateos"
iso_label="DEBATEOS_$(date --date="@{source_date_epoch}" +%Y%m)"
iso_publisher="DebateOS"
iso_application="DebateOS Arch Installer"
iso_version="$(date --date="@{source_date_epoch}" +%Y.%m.%d)"
install_dir="arch"
buildmodes=('iso')
bootmodes=('bios.syslinux' 'uefi.systemd-boot')
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=('-comp' 'xz' '-Xbcj' 'x86' '-b' '1M' '-Xdict-size' '1M')
file_permissions=(
  ["/etc/shadow"]="0:0:400"
  ["/root"]="0:0:750"
  ["/root/debateos-install.sh"]="0:0:755"
  ["/root/.zlogin"]="0:0:644"
)
