#!/usr/bin/env bash
# scripts/arch-build-iso.sh — DebateOS Arch ISO builder (slow gate)
#
# Builds an Arch Linux ISO from an archiso profile directory using mkarchiso
# inside a privileged Docker container.
#
# Usage:
#   SOURCE_DATE_EPOCH=<epoch> bash scripts/arch-build-iso.sh <profile-dir> <out-dir>
#
# Arguments:
#   <profile-dir>   Path to the archiso profile directory generated by the translator.
#   <out-dir>       Output directory; the .iso file will be written here.
#
# Required environment variables:
#   SOURCE_DATE_EPOCH   Unix timestamp for build determinism (BLD-03 groundwork).
#                       Derived from the resolved-speech hash by the generator
#                       (manifest.py::derive_source_date_epoch).
#                       Set automatically by arch-northstar-check.sh.
#
# Optional environment variables:
#   DEBATEOS_DOCKER_IMAGE  Override the pinned Docker image (for testing only).
#
# Exit codes:
#   0  ISO built successfully; ISO path printed to stdout on last line.
#   1  Error (bad arguments, Docker not available, mkarchiso failure).
#
# Threat model:
#   T-02-12: --privileged is required by mkarchiso (pacstrap uses bind mounts
#             that need CAP_SYS_ADMIN). This is the ONLY place in the build
#             pipeline that uses a privileged container. See 02-RESEARCH.md Pitfall 1.
#   T-02-13: The Docker image is pinned by sha256 digest.
#             Re-verify quarterly: docker pull archlinux:base-devel &&
#             docker inspect --format='{{index .RepoDigests 0}}'
#             Update DOCKER_IMAGE below and translators/arch/Dockerfile.
#
# Source: 02-RESEARCH.md Docker Invocation Pattern + Anti-Patterns.

set -euo pipefail

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Digest-pinned archlinux:base-devel (VERIFIED 2026-06-12, archiso 88-1).
# Dated tag for human reference: base-devel-20260607.0.541780 (same image).
# SECURITY: Update this digest quarterly — stale image = stale packages in ISO (T-02-13).
readonly _DEFAULT_DOCKER_IMAGE="archlinux:base-devel@sha256:dd60dfcca90f1ee6c2dd265ed27062070a1fb2e3b307723838a9d97741284722"

DOCKER_IMAGE="${DEBATEOS_DOCKER_IMAGE:-$_DEFAULT_DOCKER_IMAGE}"

# ---------------------------------------------------------------------------
# Argument validation
# ---------------------------------------------------------------------------

if [[ $# -ne 2 ]]; then
    echo "ERROR: wrong number of arguments" >&2
    echo "Usage: SOURCE_DATE_EPOCH=<epoch> $0 <profile-dir> <out-dir>" >&2
    exit 1
fi

PROFILE_DIR="${1}"
OUT_DIR="${2}"

if [[ -z "${SOURCE_DATE_EPOCH:-}" ]]; then
    echo "ERROR: SOURCE_DATE_EPOCH environment variable is required" >&2
    echo "  Derive it from the resolved-speech hash:" >&2
    echo "    SOURCE_DATE_EPOCH=\$(python3 -c \"" >&2
    echo "      import hashlib, struct, json, sys" >&2
    echo "      d = hashlib.sha256(open(sys.argv[1]).read().encode()).digest()" >&2
    echo "      print((1577836800 + struct.unpack('>I', d[:4])[0] % (2208988800-1577836800)))" >&2
    echo "    \" resolved.json)" >&2
    exit 1
fi

if [[ ! -d "${PROFILE_DIR}" ]]; then
    echo "ERROR: profile directory does not exist: ${PROFILE_DIR}" >&2
    exit 1
fi

if [[ ! -f "${PROFILE_DIR}/profiledef.sh" ]]; then
    echo "ERROR: ${PROFILE_DIR}/profiledef.sh not found — not a valid archiso profile" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Docker availability check
# ---------------------------------------------------------------------------

if ! command -v docker &>/dev/null; then
    echo "ERROR: docker not found in PATH" >&2
    echo "  Install Docker: https://docs.docker.com/engine/install/" >&2
    exit 1
fi

if ! docker info &>/dev/null; then
    echo "ERROR: docker daemon is not running or not accessible" >&2
    echo "  Try: sudo systemctl start docker" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------

mkdir -p "${OUT_DIR}"

PROFILE_ABS="$(realpath "${PROFILE_DIR}")"
OUT_ABS="$(realpath "${OUT_DIR}")"

echo "=== DebateOS Arch ISO Build ==="
echo "  Profile:           ${PROFILE_ABS}"
echo "  Output dir:        ${OUT_ABS}"
echo "  SOURCE_DATE_EPOCH: ${SOURCE_DATE_EPOCH}"
echo "  Docker image:      ${DOCKER_IMAGE}"
echo ""
echo "  NOTE: This is a slow gate (20-40 min). Log is streamed below."
echo "  NOTE: --privileged is required by mkarchiso (T-02-12 — see script header)."
echo ""

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

# Run mkarchiso inside the privileged archlinux container.
# Mounts:
#   /profile  — profile dir (read-only; the generator writes it; we only read)
#   /out      — output dir (read-write; mkarchiso writes the .iso here)
# -w /tmp/work — work directory inside the container (cleaned up with --rm)
#
# pacman -Sy archiso: sync and install archiso in the container on each run.
# We do not bake archiso into a custom image layer to avoid stale tool caches.
# This adds ~30s overhead but ensures we always use the latest archiso 88-1.

docker run \
    --privileged \
    --rm \
    --name "debateos-arch-build-$$" \
    -v "${PROFILE_ABS}:/debateos-overlay:ro" \
    -v "${OUT_ABS}:/out" \
    -e "SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}" \
    "${DOCKER_IMAGE}" \
    bash -c "
        set -euo pipefail
        echo '[arch-build] Updating package DB and installing archiso...'
        pacman -Sy --noconfirm archiso 2>&1 | tail -5
        pacman -Q archiso
        echo '[arch-build] Copying releng baseline profile...'
        # Use the releng baseline as the foundation (02-RESEARCH.md: Minimal Deviation from releng).
        # The generator overlay only provides targeted modifications on top of releng:
        #   - packages.x86_64 (live-env set)
        #   - airootfs/root/debateos-install.sh (0755)
        #   - airootfs/root/.zlogin (installer hook)
        #   - airootfs/etc/systemd/user/ (first-run units)
        #   - build-manifest.json (runtime data for installer)
        #   - profiledef.sh (iso_name/bootmodes/file_permissions)
        #   - pacman.conf (variant repos injected)
        # All other releng files (syslinux/, efiboot/, autologin conf, etc.) come from baseline.
        cp -r /usr/share/archiso/configs/releng /profile
        # Apply the DebateOS generator overlay on top of the releng baseline.
        # rsync-style: overlay wins on conflict (our profiledef, packages, installer override releng's).
        cp -r /debateos-overlay/. /profile/
        echo '[arch-build] Profile overlay applied. Contents:'
        ls /profile/
        echo '[arch-build] Running mkarchiso...'
        mkarchiso -v -w /tmp/work -o /out /profile
        echo '[arch-build] Build complete.'
        ls -lh /out/*.iso 2>/dev/null || echo '[arch-build] WARNING: no .iso found in /out'
    "

# ---------------------------------------------------------------------------
# Report result
# ---------------------------------------------------------------------------

ISO_FILES=("${OUT_ABS}"/*.iso)
if [[ ${#ISO_FILES[@]} -eq 0 || ! -f "${ISO_FILES[0]}" ]]; then
    echo "ERROR: no .iso file found in ${OUT_ABS} after build" >&2
    exit 1
fi

echo ""
echo "=== BUILD COMPLETE ==="
for ISO in "${OUT_ABS}"/*.iso; do
    echo "  ISO: ${ISO}"
    ls -lh "${ISO}"
done
echo ""
# Print just the ISO path on the last line for programmatic use
echo "${ISO_FILES[0]}"
