#!/usr/bin/env bash
# scripts/debian-build-iso.sh — DebateOS Debian ISO builder (slow gate)
#
# Builds a Debian live/installer ISO from a live-build config/ tree using lb build
# inside a privileged Docker container.
#
# ============================= HOST ENVIRONMENT NOTE =============================
# FULL lb BUILD IS DEFERRED-TO-CAPABLE-HOST (same policy as scripts/arch-build-iso.sh).
#
# This Proxmox VE host (kernel 6.17.4-2-pve) CANNOT run lb build: the lb chroot
# stage mounts devtmpfs and loop devices which Proxmox's container policy blocks.
# VERIFIED in 04-RESEARCH.md §Host Environment: lb build fails with "mount: permission
# denied" at the chroot/test-dev-null step even inside a --privileged Docker container.
#
# Use --skip-iso to run the profile-emission validation only (the default intent on
# this host). The equivalence gate (scripts/dual-foundation-check.sh --skip-iso) runs
# Steps 1-5 including structural validation and is the DEB-02 phase gate.
#
# To run the full build on a compatible host:
#   - Standard Linux host (bare metal, KVM VM, or cloud VM without Proxmox restrictions)
#   - Docker >= 24.x with --privileged support and unrestricted loop devices
#   - Run: SOURCE_DATE_EPOCH=<epoch> bash scripts/debian-build-iso.sh <config-tree-dir> <out-dir>
# =================================================================================
#
# Usage:
#   SOURCE_DATE_EPOCH=<epoch> bash scripts/debian-build-iso.sh <config-tree-dir> <out-dir>
#   bash scripts/debian-build-iso.sh <config-tree-dir> <out-dir> --skip-iso
#
# Arguments:
#   <config-tree-dir>  Path to the live-build config/ tree directory generated by
#                      translators/debian/translate (the parent dir containing config/).
#   <out-dir>          Output directory; the .iso file will be written here.
#
# Required environment variables (unless --skip-iso):
#   SOURCE_DATE_EPOCH  Unix timestamp for build determinism (BLD-03 groundwork).
#                      Derived from the resolved-speech hash by the generator
#                      (manifest.py::derive_source_date_epoch).
#                      Set automatically by dual-foundation-check.sh.
#
# Options:
#   --skip-iso         Skip lb build; only validate the config/ tree structure
#                      (runs scripts/debian-validate-iso.sh). Useful on hosts that
#                      cannot run lb build (e.g., this Proxmox VE host).
#
# Optional environment variables:
#   DEBATEOS_DEBIAN_DOCKER_IMAGE  Override the pinned Docker image (for testing only).
#
# Exit codes:
#   0  ISO built successfully (or --skip-iso validation passed).
#   1  Error (bad arguments, Docker not available, lb build failure, validation failed).
#
# Threat model:
#   T-04-12: --privileged is required by lb build (chroot bind mounts need CAP_SYS_ADMIN
#             and loop device access). This is the ONLY place in the Debian build pipeline
#             that uses a privileged container. See 04-RESEARCH.md §Host Environment.
#   T-04-13: The Docker image is pinned by sha256 digest.
#             Re-verify quarterly: docker pull debian:stable &&
#             docker inspect --format='{{index .RepoDigests 0}}'
#             Update DOCKER_IMAGE below and translators/debian/Dockerfile.
#
# Source: mirrors scripts/arch-build-iso.sh structure. 04-05-PLAN.md Task 2.

set -euo pipefail

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Digest-pinned debian:stable (VERIFIED 2026-06-13, live-build 1:20250505+deb13u1).
# SECURITY: Update this digest quarterly — stale image = stale packages in ISO (T-04-13).
# Re-verify: docker pull debian:stable && docker inspect --format='{{index .RepoDigests 0}}'
readonly _DEFAULT_DOCKER_IMAGE="debian:stable@sha256:fa0ca9c113cbc97c1e2eb40d7012b43bdfb70abe4218229c366de911c5b32cd2"

DOCKER_IMAGE="${DEBATEOS_DEBIAN_DOCKER_IMAGE:-$_DEFAULT_DOCKER_IMAGE}"

# ---------------------------------------------------------------------------
# Options
# ---------------------------------------------------------------------------

SKIP_ISO=false

# Parse args, separating positional from flags
POSITIONAL=()
for arg in "$@"; do
    case "${arg}" in
        --skip-iso) SKIP_ISO=true ;;
        -h|--help)
            echo "Usage: SOURCE_DATE_EPOCH=<epoch> $0 <config-tree-dir> <out-dir> [--skip-iso]" >&2
            echo "" >&2
            echo "IMPORTANT: Full lb build is deferred-to-capable-host (see script header)." >&2
            echo "  This Proxmox VE host cannot run lb build (devtmpfs/loop restriction)." >&2
            echo "  Use --skip-iso to run structural validation only." >&2
            exit 0
            ;;
        *)
            POSITIONAL+=("${arg}")
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Argument validation
# ---------------------------------------------------------------------------

if [[ ${#POSITIONAL[@]} -ne 2 ]]; then
    echo "ERROR: wrong number of positional arguments" >&2
    echo "Usage: SOURCE_DATE_EPOCH=<epoch> $0 <config-tree-dir> <out-dir> [--skip-iso]" >&2
    exit 1
fi

CONFIG_TREE_DIR="${POSITIONAL[0]}"
OUT_DIR="${POSITIONAL[1]}"

if [[ ! -d "${CONFIG_TREE_DIR}" ]]; then
    echo "ERROR: config tree directory does not exist: ${CONFIG_TREE_DIR}" >&2
    exit 1
fi

# Determine the config/ subdirectory (same logic as debian-validate-iso.sh)
if [[ -d "${CONFIG_TREE_DIR}/config" ]]; then
    CONFIG_DIR="${CONFIG_TREE_DIR}/config"
else
    echo "ERROR: ${CONFIG_TREE_DIR}/config not found — not a valid Debian translator output" >&2
    echo "  Expected a directory with config/ produced by translators/debian/translate" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# --skip-iso path: structural validation only
# ---------------------------------------------------------------------------

if [[ "${SKIP_ISO}" == "true" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    echo "=== DebateOS Debian Build (--skip-iso: validation only) ==="
    echo "  Config tree:  ${CONFIG_TREE_DIR}"
    echo "  NOTE: lb build is deferred-to-capable-host (see script header)." >&2
    echo ""
    exec bash "${SCRIPT_DIR}/debian-validate-iso.sh" "${CONFIG_TREE_DIR}"
fi

# ---------------------------------------------------------------------------
# Full build path — requires SOURCE_DATE_EPOCH
# ---------------------------------------------------------------------------

if [[ -z "${SOURCE_DATE_EPOCH:-}" ]]; then
    echo "ERROR: SOURCE_DATE_EPOCH environment variable is required for lb build" >&2
    echo "  Derive it from the resolved-speech hash:" >&2
    echo "    SOURCE_DATE_EPOCH=\$(python3 -c \"" >&2
    echo "      import hashlib, struct" >&2
    echo "      d = hashlib.sha256(open('resolved.json', 'rb').read()).digest()" >&2
    echo "      print(1577836800 + struct.unpack('>I', d[:4])[0] % (2208988800-1577836800))" >&2
    echo "    \")" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Docker availability check
# ---------------------------------------------------------------------------

if ! command -v docker &>/dev/null; then
    echo "ERROR: docker not found in PATH" >&2
    echo "  Install Docker: https://docs.docker.com/engine/install/" >&2
    exit 1
fi

if ! docker info &>/dev/null; then
    echo "ERROR: docker daemon is not running or not accessible" >&2
    echo "  Try: sudo systemctl start docker" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------

mkdir -p "${OUT_DIR}"

CONFIG_ABS="$(realpath "${CONFIG_TREE_DIR}")"
OUT_ABS="$(realpath "${OUT_DIR}")"

echo "=== DebateOS Debian ISO Build ==="
echo "  Config tree:       ${CONFIG_ABS}"
echo "  Output dir:        ${OUT_ABS}"
echo "  SOURCE_DATE_EPOCH: ${SOURCE_DATE_EPOCH}"
echo "  Docker image:      ${DOCKER_IMAGE}"
echo ""
echo "  NOTE: This is a slow gate (20-40 min). Log is streamed below."
echo "  NOTE: --privileged is required by lb build (T-04-12 — see script header)."
echo ""
echo "  HOST COMPATIBILITY: This host (Proxmox VE) likely CANNOT complete lb build."
echo "  VERIFIED in 04-RESEARCH.md: lb build fails at chroot/test-dev-null due to"
echo "  devtmpfs/loop restriction. Continuing anyway — failure is expected on this host."
echo ""

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

# Run lb build inside the privileged Debian container.
# Mounts:
#   /debateos-config  — config/ tree dir (read-only; generator writes; we overlay)
#   /out              — output dir (read-write; lb build writes the .iso here)
# -w /build           — work directory inside the container
#
# Steps inside container:
#   1. apt-get: install live-build + dependencies
#   2. mkdir /build; copy config/ tree into /build/
#   3. lb build (auto-finds /build/config/)
#   4. Move .iso to /out/

docker run \
    --privileged \
    --rm \
    --name "debateos-debian-build-$$" \
    -v "${CONFIG_ABS}:/debateos-config:ro" \
    -v "${OUT_ABS}:/out" \
    -e "SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}" \
    "${DOCKER_IMAGE}" \
    bash -c "
        set -euo pipefail
        echo '[debian-build] Updating package DB and installing live-build...'
        apt-get update -qq
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            live-build debootstrap squashfs-tools xorriso python3 jq 2>&1 | tail -5
        lb --version
        echo '[debian-build] Copying config/ tree into build directory...'
        mkdir -p /build
        cp -r /debateos-config/. /build/
        ls /build/
        echo '[debian-build] Running lb build...'
        cd /build
        lb build 2>&1
        echo '[debian-build] Build complete. Moving ISO to /out/'
        find /build -name '*.iso' -exec cp {} /out/ \;
        ls -lh /out/*.iso 2>/dev/null || echo '[debian-build] WARNING: no .iso found in /build'
    "

# ---------------------------------------------------------------------------
# Report result
# ---------------------------------------------------------------------------

ISO_FILES=("${OUT_ABS}"/*.iso)
if [[ ${#ISO_FILES[@]} -eq 0 || ! -f "${ISO_FILES[0]}" ]]; then
    echo "ERROR: no .iso file found in ${OUT_ABS} after build" >&2
    echo "  If the build failed due to loop/devtmpfs, see the HOST COMPATIBILITY note above." >&2
    exit 1
fi

echo ""
echo "=== BUILD COMPLETE ==="
for ISO in "${OUT_ABS}"/*.iso; do
    echo "  ISO: ${ISO}"
    ls -lh "${ISO}"
done
echo ""
# Print just the ISO path on the last line for programmatic use
echo "${ISO_FILES[0]}"
