#!/usr/bin/env bash
# scripts/debian-validate-iso.sh — DebateOS Debian config/ tree structural validator
#
# Validates the structural integrity of a live-build config/ tree generated by the
# Debian translator (translators/debian/). This is a HOST-RUNNABLE check that does
# not require Docker, loop devices, or a privileged container.
#
# On this host (Proxmox VE with devtmpfs restriction) this is the highest build-time
# validation gate achievable without Docker ISO build — same policy as the
# --skip-iso path in arch-validate-iso.sh / arch-northstar-check.sh.
#
# Checks:
#   1. preseed.cfg present + contains d-i directives (d-i automation lines)
#   2. Chroot hook present (9000-debateos-apply.hook.chroot) + executable (0755)
#   3. Package-lists file present (debateos.list.chroot_install) + non-empty
#   4. build-manifest.json present + valid JSON
#
# Usage:
#   bash scripts/debian-validate-iso.sh <config-tree-dir>
#
# Arguments:
#   <config-tree-dir>  Path to the directory containing the live-build config/
#                      subtree (the output directory from translators/debian/translate).
#                      Alternatively, the config-tree-dir may itself be named "config/"
#                      — the validator handles both layouts.
#
# Examples:
#   # After running dual-foundation-check.sh or translators/debian/translate:
#   bash scripts/debian-validate-iso.sh /tmp/debian-profile
#
#   # Pipe into dual-foundation-check.sh Step 5 (called automatically from there)
#
# Exit codes:
#   0   All structural checks passed.
#   1   One or more checks failed (details printed to stderr).
#
# Source: mirrors arch-validate-iso.sh structure (scripts/02-PLAN-05.md pattern).
# Source: 04-05-PLAN.md Task 1.

set -euo pipefail

# ---------------------------------------------------------------------------
# Argument validation
# ---------------------------------------------------------------------------

if [[ $# -ne 1 ]]; then
    echo "ERROR: wrong number of arguments" >&2
    echo "Usage: $0 <config-tree-dir>" >&2
    exit 1
fi

TREE_DIR="${1}"

if [[ ! -d "${TREE_DIR}" ]]; then
    echo "ERROR: config tree directory not found: ${TREE_DIR}" >&2
    exit 1
fi

# Determine the config/ subdirectory.
# The translator emits: <out-dir>/config/... and <out-dir>/build-manifest.json
# Accept both <out-dir> and <out-dir>/config layouts.
if [[ -d "${TREE_DIR}/config" ]]; then
    CONFIG_DIR="${TREE_DIR}/config"
    MANIFEST_JSON="${TREE_DIR}/build-manifest.json"
elif [[ "$(basename "${TREE_DIR}")" == "config" && -d "${TREE_DIR}/includes.installer" ]]; then
    CONFIG_DIR="${TREE_DIR}"
    MANIFEST_JSON="${TREE_DIR}/../build-manifest.json"
else
    echo "ERROR: neither ${TREE_DIR}/config nor ${TREE_DIR} looks like a live-build config/ tree" >&2
    echo "  Expected at minimum: includes.installer/ and package-lists/ subdirectories" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------

PASS=0
FAIL=0

pass() { echo "  [PASS] $*"; ((PASS++)) || true; }
fail() { echo "  [FAIL] $*" >&2; ((FAIL++)) || true; }

echo "=== DebateOS Debian Config/ Tree Structural Validation ==="
echo "  Tree dir:  ${TREE_DIR}"
echo "  Config:    ${CONFIG_DIR}"
echo ""

# ---------------------------------------------------------------------------
# Check 1: preseed.cfg present + contains d-i directives
# ---------------------------------------------------------------------------

echo "--- Check 1: preseed.cfg ---"
PRESEED="${CONFIG_DIR}/includes.installer/preseed.cfg"
if [[ -f "${PRESEED}" ]]; then
    pass "preseed.cfg found at ${PRESEED}"
    if grep -q 'd-i' "${PRESEED}"; then
        DI_LINES="$(grep -c 'd-i' "${PRESEED}" || echo 0)"
        pass "preseed.cfg contains d-i directives (${DI_LINES} lines)"
    else
        fail "preseed.cfg has no 'd-i' lines — may not be a valid preseed"
    fi
    if grep -q 'd-i partman' "${PRESEED}" || grep -q 'd-i netcfg' "${PRESEED}"; then
        pass "preseed.cfg contains partman/netcfg directives (d-i automation)"
    else
        fail "preseed.cfg missing partman or netcfg d-i directives"
    fi
else
    fail "preseed.cfg NOT FOUND at ${PRESEED}"
    echo "  Expected path: ${PRESEED}" >&2
fi
echo ""

# ---------------------------------------------------------------------------
# Check 2: Chroot hook present + executable (0755)
# ---------------------------------------------------------------------------

echo "--- Check 2: chroot hook ---"
HOOK="${CONFIG_DIR}/hooks/live/9000-debateos-apply.hook.chroot"
if [[ -f "${HOOK}" ]]; then
    pass "chroot hook found: ${HOOK}"
    if [[ -x "${HOOK}" ]]; then
        pass "chroot hook is executable (0755)"
    else
        fail "chroot hook is NOT executable — lb build requires executable hooks"
    fi
    # The hook must reference apt-get for package installs and systemctl for services
    if grep -q 'apt-get' "${HOOK}" || grep -q 'apt ' "${HOOK}"; then
        pass "chroot hook references apt-get (package installation mechanic)"
    else
        fail "chroot hook does not reference apt-get — package install may not run"
    fi
else
    fail "chroot hook NOT FOUND at ${HOOK}"
fi
echo ""

# ---------------------------------------------------------------------------
# Check 3: Package-lists present + non-empty
# ---------------------------------------------------------------------------

echo "--- Check 3: package-lists ---"
PKGLIST_DIR="${CONFIG_DIR}/package-lists"
if [[ -d "${PKGLIST_DIR}" ]]; then
    # Use find to safely count .chroot_install files
    PKGLIST_COUNT="$(find "${PKGLIST_DIR}" -name "*.chroot_install" 2>/dev/null | wc -l | tr -d ' ')"
    if [[ "${PKGLIST_COUNT}" -gt 0 ]]; then
        pass "package-lists: ${PKGLIST_COUNT} .chroot_install file(s) found"
        # Check main list contains packages
        MAIN_LIST="${PKGLIST_DIR}/debateos.list.chroot_install"
        if [[ -f "${MAIN_LIST}" ]]; then
            PKG_COUNT="$(grep -cvE '^#|^[[:space:]]*$' "${MAIN_LIST}" 2>/dev/null || echo 0)"
            if [[ "${PKG_COUNT}" -gt 0 ]]; then
                pass "package-lists/debateos.list.chroot_install: ${PKG_COUNT} package(s)"
            else
                fail "package-lists/debateos.list.chroot_install is empty"
            fi
        else
            fail "package-lists/debateos.list.chroot_install not found (expected main list)"
        fi
    else
        fail "package-lists: no .chroot_install files found in ${PKGLIST_DIR}"
    fi
else
    fail "package-lists directory not found at ${PKGLIST_DIR}"
fi
echo ""

# ---------------------------------------------------------------------------
# Check 4: build-manifest.json present + valid JSON
# ---------------------------------------------------------------------------

echo "--- Check 4: build-manifest.json ---"
if [[ -f "${MANIFEST_JSON}" ]]; then
    pass "build-manifest.json found"
    if python3 -m json.tool "${MANIFEST_JSON}" >/dev/null 2>&1; then
        pass "build-manifest.json: valid JSON"
        # Check target_packages field
        if python3 -c "
import json, sys
m = json.load(open('${MANIFEST_JSON}'))
pkgs = m.get('target_packages', [])
if pkgs:
    print(f'  target_packages ({len(pkgs)} pkgs): {pkgs[:5]}')
    sys.exit(0)
else:
    sys.exit(1)
" 2>/dev/null; then
            pass "build-manifest.json: target_packages field present and non-empty"
        else
            fail "build-manifest.json: target_packages is missing or empty"
        fi
    else
        fail "build-manifest.json: NOT valid JSON"
    fi
else
    fail "build-manifest.json not found (expected at ${MANIFEST_JSON})"
fi
echo ""

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

echo "=== DEBIAN VALIDATION SUMMARY ==="
echo "  Passed: ${PASS}"
echo "  Failed: ${FAIL}"
echo ""

if [[ ${FAIL} -eq 0 ]]; then
    echo "  RESULT: DEBIAN CONFIG/ TREE STRUCTURAL VALIDATION PASSED"
    echo "  The config/ tree is structurally valid for lb build."
    echo "  Full ISO build requires a host with loop devices / devtmpfs (see debian-build-iso.sh)."
    exit 0
else
    echo "  RESULT: DEBIAN CONFIG/ TREE VALIDATION FAILED (${FAIL} check(s) failed)" >&2
    exit 1
fi
