#!/bin/bash
# config/hooks/live/9000-debateos-apply.hook.chroot
# Generated by translators/debian/profile.py from build-manifest.json
# Source: live-team.pages.debian.net/live-manual (Pattern 1)
# Security: T-04-06 — all opinion data via build-manifest.json; %%SENTINEL%% replacement only.
# Security: T-04-05 — file_asset dst paths are sanitized by _sanitize_dst before emission.
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

echo "[DebateOS] Applying opinion-driven configuration in chroot..."

# ---------------------------------------------------------------------------
# Install target packages (from manifest.target_packages via BuildManifest)
# ---------------------------------------------------------------------------
apt-get update -qq
apt-get install -y --no-install-recommends \
%%PACKAGES%%

# ---------------------------------------------------------------------------
# Remove packages (from manifest.remove_packages)
# ---------------------------------------------------------------------------
%%REMOVE_PACKAGES_STANZA%%

# ---------------------------------------------------------------------------
# Deploy file assets (from manifest.file_assets)
# All dst paths are relative to the chroot root; validated by _sanitize_dst.
# ---------------------------------------------------------------------------
%%FILE_ASSET_STANZA%%

# ---------------------------------------------------------------------------
# Enable systemd services (from manifest.system_services where enable=true)
# ---------------------------------------------------------------------------
%%SERVICE_ENABLE_STANZA%%

# ---------------------------------------------------------------------------
# Apply sysctl drop-ins (from manifest.sysctl_params)
# ---------------------------------------------------------------------------
%%SYSCTL_STANZA%%

# ---------------------------------------------------------------------------
# Apply kernel parameters (from manifest.kernel_params via GRUB_CMDLINE_LINUX)
# ---------------------------------------------------------------------------
%%KERNEL_PARAM_STANZA%%

# ---------------------------------------------------------------------------
# Add user to groups (from manifest.group_memberships)
# Groups are created if absent; user addition is deferred to install time.
# ---------------------------------------------------------------------------
%%GROUP_MEMBERSHIP_STANZA%%

echo "[DebateOS] Chroot opinion application complete."
