#!/bin/bash
# config/hooks/live/9000-debateos-apply.hook.chroot
# Generated by translators/debian/profile.py
# Source: live-team.pages.debian.net/live-manual (Pattern 1)
# Security: T-04-06 — all opinion data read from build-manifest.json via jq at chroot
#           time (CR-01 safe pattern); NO curator-authored strings embedded in shell
#           command position.
# Security: T-04-05 — file_asset dst paths are sanitized by _sanitize_dst before emission.
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

echo "[DebateOS] Applying opinion-driven configuration in chroot..."

MANIFEST="/build-manifest.json"

# ---------------------------------------------------------------------------
# Install target packages (read from build-manifest.json via jq — T-04-06/CR-01)
# ---------------------------------------------------------------------------
%%PACKAGES_STANZA%%

# ---------------------------------------------------------------------------
# Remove packages (read from build-manifest.json via jq — T-04-06/CR-01)
# ---------------------------------------------------------------------------
%%REMOVE_PACKAGES_STANZA%%

# ---------------------------------------------------------------------------
# Deploy file assets (from manifest.file_assets)
# All dst paths are relative to the chroot root; validated by _sanitize_dst.
# ---------------------------------------------------------------------------
%%FILE_ASSET_STANZA%%

# ---------------------------------------------------------------------------
# Enable systemd services (read from build-manifest.json via jq — T-04-06/CR-01)
# Service names are never interpolated into shell command position; jq + while read
# ensures each name is passed as a separate quoted argument to systemctl enable.
# ---------------------------------------------------------------------------
if command -v jq >/dev/null 2>&1 && [ -f "${MANIFEST}" ]; then
    while IFS= read -r svc; do
        [ -n "${svc}" ] || continue
        systemctl enable "${svc}"
    done < <(jq -r '.system_services[] | select(.enable==true) | .name' "${MANIFEST}" 2>/dev/null || true)
else
%%SERVICE_ENABLE_FALLBACK%%
fi

# ---------------------------------------------------------------------------
# Apply sysctl drop-ins (read from build-manifest.json via jq — T-04-06/CR-01)
# Key/value pairs are passed via printf '%s\n' (never unquoted interpolation).
# ---------------------------------------------------------------------------
if command -v jq >/dev/null 2>&1 && [ -f "${MANIFEST}" ]; then
    mkdir -p /etc/sysctl.d
    jq -r '.sysctl_params[] | .drop_in_file + "\t" + .key + " = " + .value' \
        "${MANIFEST}" 2>/dev/null | \
    while IFS=$'\t' read -r drop_in kv; do
        [ -n "${drop_in}" ] || continue
        printf '%s\n' "${kv}" >> "/etc/sysctl.d/${drop_in}"
    done || true
else
%%SYSCTL_FALLBACK%%
fi

# ---------------------------------------------------------------------------
# Apply kernel parameters (from manifest.kernel_params via GRUB_CMDLINE_LINUX)
# ---------------------------------------------------------------------------
%%KERNEL_PARAM_STANZA%%

# ---------------------------------------------------------------------------
# Add user to groups (read from build-manifest.json via jq — T-04-06/CR-01)
# Group names are never interpolated into shell command position; jq + while read
# ensures each name is passed as a separate quoted argument to groupadd.
# ---------------------------------------------------------------------------
if command -v jq >/dev/null 2>&1 && [ -f "${MANIFEST}" ]; then
    while IFS= read -r grp; do
        [ -n "${grp}" ] || continue
        getent group "${grp}" >/dev/null 2>&1 || groupadd "${grp}"
    done < <(jq -r '.group_memberships[] | .group' "${MANIFEST}" 2>/dev/null || true)
else
%%GROUP_MEMBERSHIP_FALLBACK%%
fi

echo "[DebateOS] Chroot opinion application complete."
