_preseed_V1
# config/includes.installer/preseed.cfg
# Generated by translators/debian/profile.py from build-manifest.json
# Source: www.debian.org/releases/stable/example-preseed.txt (Pattern 2)
# Security: T-04-08 — password uses crypt hash (%%HASHED_PASSWORD%%), never plaintext.

# Locale and keyboard
d-i debian-installer/locale string en_US.UTF-8
d-i keyboard-configuration/xkb-keymap select us

# Network (DHCP auto-configure)
d-i netcfg/choose_interface select auto
d-i netcfg/get_hostname string debian
d-i netcfg/get_domain string local

# Disk partitioning (auto — LVM on first disk)
d-i partman-auto/method string lvm
d-i partman-auto-lvm/guided_size string max
d-i partman-auto/choose_recipe select atomic
d-i partman/confirm_write_new_label boolean true
d-i partman/confirm boolean true
d-i partman/confirm_nooverwrite boolean true
d-i partman-lvm/confirm boolean true
d-i partman-lvm/confirm_nooverwrite boolean true
d-i partman-md/confirm boolean true
d-i partman-md/confirm_nooverwrite boolean true

# User account
# Security (T-04-08): password is a crypt-hashed value, never plaintext.
# Replace %%USERNAME%%, %%USER_FULLNAME%%, %%HASHED_PASSWORD%% at build time.
d-i passwd/root-login boolean false
d-i passwd/user-fullname string %%USER_FULLNAME%%
d-i passwd/username string %%USERNAME%%
d-i passwd/user-password-crypted password %%HASHED_PASSWORD%%
d-i passwd/user-default-groups string audio video sudo

# Clock and timezone
d-i clock-setup/utc boolean true
d-i time/zone string UTC
d-i clock-setup/ntp boolean true

# Package selection (d-i level only; opinion packages are in the chroot hook)
d-i pkgsel/include string %%PKGSEL_PACKAGES%%
tasksel tasksel/first multiselect standard

# Skip popularity-contest
popularity-contest popularity-contest/participate boolean false

# Boot loader (GRUB2)
d-i grub-installer/only_debian boolean true
d-i grub-installer/bootdev string default

# Minimal late_command: the chroot hook has already applied opinions
# at lb build time; no network needed here.
d-i preseed/late_command string echo "DebateOS preseed complete"

# Finish
d-i finish-install/reboot_in_progress note
